covid:
  host: "disease.sh"
  port: "80"
  timeout: "30000"

cassandra:
  host: "localhost"
  port: "9042"
  keyspace: "covid"
  username: "cassandra"
  password: "![l8O5tvyOtJflO74FRzI5qQ==]"
  cluster: "test"
  nodes: "127.0.0.1,127.0.0.2"
  replication_factor: "2"
  

kafka:
  bootstrapServers: "localhost:9092,localhost:9093,localhost:9094"
  topic: "covid"